#!/usr/bin/env bash
#
# AgentHN GPU demo-server orchestrator — ONE script for the demo box.
#
# Lifecycle (Prime Intellect 1×A100, after `git clone` + repo set up — see
# "What you need on the server" in scripts/README_GPU.md):
#
#   1. Start the FastAPI backend (loads the Doc-to-LoRA model on the GPU).
#   2. Capture REAL demo outputs into static fixtures; commit + push.
#   3. Open a public tunnel; point the live site at it (config.js); commit + push.
#   4. Serve — GPU requests from the website queue on the shared model lock —
#      until SWITCH_AT (default 8:55pm PT 6/20).
#   5. At SWITCH_AT: revert config.js to recorded-fixtures mode (remove the GPU
#      URL); commit + push. The site now replays the captured runs.
#   6. At KILL_AT (default 9:00pm PT): kill the tunnel + server.
#   7. Power off the instance (set DO_SHUTDOWN=0 to skip).
#
# Everything past step 2 is best-effort and guarded; a transient failure won't
# abort the run. Override any knob via env, e.g. `SWITCH_AT=... DO_SHUTDOWN=0 ...`.
set -uo pipefail

cd "$(git rev-parse --show-toplevel)" || { echo "not a git repo"; exit 1; }

# ----------------------------- config -----------------------------
PORT="${PORT:-8000}"
BRANCH="${BRANCH:-main}"
SWITCH_AT="${SWITCH_AT:-2026-06-20T20:55:00-07:00}"   # site -> fixtures
KILL_AT="${KILL_AT:-2026-06-20T21:00:00-07:00}"       # kill GPU server
CAPTURE_SIZES="${CAPTURE_SIZES:-small medium}"
DO_SHUTDOWN="${DO_SHUTDOWN:-1}"                         # poweroff at the end
CONFIG_JS="src/agenthn/webapp/static/config.js"
CUTOFF_JS='Date.parse("2026-06-20T21:00:00-07:00")'    # browser-side backstop
LOGDIR="logs"; mkdir -p "$LOGDIR" "src/agenthn/webapp/static/fixtures"

# Python interpreter: the doc-to-lora venv has the full GPU stack.
PY="${PY:-/home/ubuntu/doc-to-lora/.venv/bin/python}"
if [ ! -x "$PY" ]; then
  for c in /root/doc-to-lora/.venv/bin/python "$(command -v python3)"; do
    [ -x "$c" ] && PY="$c" && break
  done
fi
echo "using python: $PY"

# ----------------------------- helpers -----------------------------
epoch() { date -d "$1" +%s 2>/dev/null || \
  python3 -c 'import sys,datetime;print(int(datetime.datetime.fromisoformat(sys.argv[1]).timestamp()))' "$1"; }
SWITCH_TS="$(epoch "$SWITCH_AT")"; KILL_TS="$(epoch "$KILL_AT")"

git config user.name  >/dev/null 2>&1 || git config user.name  "AgentHN GPU box"
git config user.email >/dev/null 2>&1 || git config user.email "gpu@agenthn.local"

push() { # $1 = commit message
  git add -A
  if git diff --cached --quiet; then echo "(nothing to commit)"; return 0; fi
  git commit -m "$1" -m "Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>" >/dev/null
  git pull --rebase origin "$BRANCH" >/dev/null 2>&1 || true
  git push origin "$BRANCH" && echo "pushed: $1" || echo "!! push failed: $1"
}

write_config() { # $1 = backend url ("" for recorded-fixtures mode)
  local url="$1"
  if [ -n "$url" ]; then
    cat > "$CONFIG_JS" <<EOF
/* AgentHN runtime config — AUTO-GENERATED by scripts/run_demo_server.sh.
 * Live GPU backend is up; demos call it directly. Reverted to "" at SWITCH_AT. */
window.AGENTHN_CONFIG = {
  backend: "$url",
  cutoff: $CUTOFF_JS,
};
EOF
  else
    cat > "$CONFIG_JS" <<EOF
/* AgentHN runtime config — recorded-fixtures mode.
 * GPU backend is offline; the hardcoded tunnel URL has been removed. Demos
 * replay the captured runs in /fixtures. The cutoff is a browser-side backstop. */
window.AGENTHN_CONFIG = {
  backend: "",
  cutoff: $CUTOFF_JS,
};
EOF
  fi
}

SERVER_PID=""; TUNNEL_PID=""
start_server() {
  PYTHONPATH=src "$PY" -m uvicorn agenthn.webapp.app:app \
    --host 0.0.0.0 --port "$PORT" >"$LOGDIR/server.log" 2>&1 &
  SERVER_PID=$!
  echo "server pid=$SERVER_PID (log: $LOGDIR/server.log)"
}
wait_health() {
  for _ in $(seq 1 180); do
    curl -sf "http://127.0.0.1:$PORT/api/health" >/dev/null 2>&1 && { echo "backend healthy"; return 0; }
    kill -0 "$SERVER_PID" 2>/dev/null || { echo "!! server exited early — see $LOGDIR/server.log"; return 1; }
    sleep 5
  done
  echo "!! server never became healthy"; return 1
}
cleanup() {
  [ -n "$TUNNEL_PID" ] && kill "$TUNNEL_PID" 2>/dev/null
  [ -n "$SERVER_PID" ] && kill "$SERVER_PID" 2>/dev/null
}
trap cleanup INT TERM

# Resolve a tunnel binary (cloudflared preferred; auto-download if missing).
resolve_tunnel() {
  if command -v cloudflared >/dev/null 2>&1; then CFD="cloudflared"; return 0; fi
  if [ -x "./bin/cloudflared" ]; then CFD="./bin/cloudflared"; return 0; fi
  echo "cloudflared not found — downloading static binary…"
  mkdir -p bin
  if curl -fsSL -o bin/cloudflared \
      https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64; then
    chmod +x bin/cloudflared; CFD="./bin/cloudflared"; return 0
  fi
  echo "!! could not get cloudflared; install it or set up ngrok manually"; return 1
}

# ----------------------------- run -----------------------------
echo "== 1. start backend =="
start_server
wait_health || { echo "aborting"; cleanup; exit 1; }

echo "== 2. capture fixtures =="
CAPTURE_BASE="http://127.0.0.1:$PORT" CAPTURE_SIZES="$CAPTURE_SIZES" "$PY" scripts/capture_fixtures.py \
  && push "Capture demo fixtures from live GPU run" \
  || echo "!! capture step had problems — continuing"

echo "== 3. open public tunnel =="
URL=""
if resolve_tunnel; then
  "$CFD" tunnel --no-autoupdate --url "http://localhost:$PORT" >"$LOGDIR/tunnel.log" 2>&1 &
  TUNNEL_PID=$!
  for _ in $(seq 1 60); do
    URL="$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' "$LOGDIR/tunnel.log" | head -1)"
    [ -n "$URL" ] && break
    sleep 2
  done
fi

if [ -n "$URL" ]; then
  echo "tunnel up: $URL"
  echo "== 4. point site at live GPU backend =="
  write_config "$URL"
  push "Point site at live GPU backend"
else
  echo "!! no tunnel URL — site stays in recorded-fixtures mode (fixtures already pushed)"
fi

echo "== 5. serving until $SWITCH_AT (GPU requests queue on the shared model lock) =="
while [ "$(date +%s)" -lt "$SWITCH_TS" ]; do
  if ! kill -0 "$SERVER_PID" 2>/dev/null; then
    echo "!! backend died — restarting"; start_server; wait_health || true
  fi
  sleep 15
done

echo "== 6. switch site to recorded fixtures =="
write_config ""
push "Switch site to recorded fixtures; remove live GPU URL"

echo "== 7. holding until $KILL_AT, then killing GPU server =="
while [ "$(date +%s)" -lt "$KILL_TS" ]; do sleep 10; done
cleanup
echo "server + tunnel stopped"

echo "== 8. shutdown =="
if [ "$DO_SHUTDOWN" = "1" ]; then
  echo "powering off instance…"
  sudo shutdown -h now 2>/dev/null || shutdown -h now 2>/dev/null || sudo poweroff || poweroff
else
  echo "DO_SHUTDOWN=0 — leaving instance running"
fi
